# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1,16).reshape(3,5)

In [ ]:
print(f"Dimensions of the matrix: {A.ndim}")

In [ ]:
print(f"shape of the matrix: {A.shape}")

In [ ]:
print(f"Size of the matrix: {A.size}")

In [ ]:
print(f"Size of the matrix: {A.dtype}")

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B, B.shape)
print()
print(C, C.shape)

In [ ]:
# Elementwise subtraction.
print(B-C)

In [ ]:
# Elementwise multiplication.
print(B*C)

In [ ]:
# Matrix multiplication
print(B @ C)

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

In [ ]:
# Exponentiate each number elementwise (use the np.exp function).
print(np.exp(B))

In [ ]:
# Calculate the minimum value in the whole matrix.
print(np.min(B))

In [ ]:
# Calculcate the minimum value in each row.
print(np.min(B, axis=1))

In [ ]:
# Calculcate the minimum value in each column.
print(np.min(B, axis=0))

In [ ]:
# Find the index value for the minimum value in the whole matrix (hint: use np.argmin) ???????????????
print(np.argmin(B))

In [ ]:
# Find the index value for the minimum value in each row (hint: use np.argmin).
im_row = np.argmin(B, axis=1)
im_col = np.argmin(B, axis=0)
print("The index value for the minimum value in each row: ",im_row)
print("The index value for the minimum value in each column: ",im_col)

In [ ]:
# Calculate the sum for all elements.
print(np.sum(B))

In [ ]:
# Calculate the mean for each column.
print(np.mean(B, axis=0))

In [ ]:
# Calculate the median for each column.
print(np.median(B, axis=0))

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [ ]:
print("""Betyder att vi väljer hela raden (i detta fall den andra raden) 
utan att specificera vilka kolumner du vill extrahera.""")

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
print(A)

In [ ]:
for i in A:
    print(i)

In [ ]:
## iterate trough the columns
row, column = A.shape

for i in range(0, column):
    for e in range(0, row):
        print (A[e, i], f"where A[{e},{i}]")

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

In [ ]:
a = np.arange(30) 
c=a.reshape(2, 3, -1)
print(f"""[np.arange(30)] creates a 1 dimension array:
a = {a}

[b = a.reshape((2, 3, -1))] is used to reshape the 1D array into a 3D array: 
{b}

[b] has three axes defined by (2, 3, -1) 
The first axis has a size of 2
The second axis has a size of 3
The size of the third axis is determined depending on the total number of 
elements in [a] array and the sizes of the other dimensions. 
The -1 facilitates automatic determination for this dimension.""")
d = np.arange(30) 
e=d.reshape(2, 5, -1)
print(f"""Example: using d.reshape((2, 5, -1)) and the result will automatically be:
{e} """)

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
print(A+b)

# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [ ]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [ ]:
def add_mult_matrices(m_1, m_2, op):
    import numpy as np
    if not (isinstance(m_1, np.ndarray)):
        raise ValueError("Matrix 1 is not of type ndarray!")
    if not (isinstance(m_2, np.ndarray)):
        raise ValueError("Matrix 2 is not of type ndarray!")
    if op not in ('add', 'multiply'):
        raise ValueError("It must be 'add' or 'multiply' operator!")

    if op == 'add':
        if m_1.shape != m_2.shape:
            raise ValueError("Matrices have not the same shape!")
        r = m_1 + m_2
    else:
        if m_1.shape[1] != m_2.shape[0]:
            raise ValueError("Matrices do not conform for multiplication!")
        r = m_1 @ m_2

    return r


In [ ]:
print(add_mult_matrices(C, D, "add"))

In [ ]:
print(add_mult_matrices(C, D, "multiply"))

**Chap2. Question 2**

In [ ]:
print(add_mult_matrices(B, (-2)*A, "add"))

In [ ]:
print(add_mult_matrices((3*C), ((-1)*E), "add"))

In [ ]:
print(add_mult_matrices(A, C, "multiply"))

In [ ]:
print(add_mult_matrices(C, D, "multiply"))

In [ ]:
print(add_mult_matrices(C, B, "multiply"))

**Chap2. Question 3**

In [ ]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

In [ ]:
print(add_mult_matrices(A, D, "multiply"))

In [ ]:
print(add_mult_matrices(D, A, "multiply"))

**Quiz p.11, Question 2**

**Chap 6. Question 1**

In [ ]:
F = np.array([[5, 6], [4, 5]])
G = np.array([[6, 4], [3, 3]])
print(np.linalg.inv(F))
print(np.linalg.inv(G))

**Quiz p.19, Question 3**

**Chap10. Question 1 a)**

In [ ]:
J = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
K = np.array([-7, 5, 2])
print(np.linalg.solve(J, K))

**Chap10. Question 1 b)**

In [ ]:
M = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
N = np.array([1, -1, 1])
print(np.linalg.solve(M, N))

**Chap 12. Question 1**

In [ ]:
W = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
print(np.linalg.inv(W))

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [64]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [65]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [66]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
